### ISSUE TITLE
Fine tuning on Coedit

### ISSUE THREAD

**Issue by akesh1235** [vipulraheja/coedit#1]
There are 2 output/Target, How transformers can be fine tuned on multiple output?
Please acknowledge me

**Comment by vipulraheja** [comment]
Hi @akesh1235, sorry for the delay in getting back to you. Could you please clarify your question? Did you mean fine-tuning on data with multiple targets for the same source?

**Comment by akesh1235** [comment]
Thankyou for your kind reply, 
I have **2 query**, following 

1. I initially misunderstood that we should pass **2 input(incoherent sentence 1 &2) and getting 2 output (coherent sentence 1 &2)** now I got clarity that I should concatenate incoherent for input and coherent for target. **Is it right ?**

2. I saw your research paper on **Adversarial Grammar Error Correction** its amazing. Can we use **TILGAN** used for Grammar Error Correction. If not,
how can I integrate **GAN with Transformer** for Grammar Error Correction?

**Comment by vipulraheja** [comment]
I'm still not sure I still fully understand your question(s). My guess is that it should be fairly straightforward. I'd suggest you contact the TILGAN authors for clarification. This space is for CoEdIT-related issues only.

**Comment by akesh1235** [comment]
Okay Thankyou sir, Any source code for GAN-Transformer?
