### ISSUE TITLE
dataset release?

### ISSUE THREAD

**Issue by pszemraj** [vipulraheja/coedit#3]
Hi! Thank you for your great work. The models are excellent at preserving the salient content while making the requested edits. I was wondering if the dataset has already been released or will be soon? I couldn't find it when I searched just now.

**Comment by vipulraheja** [comment]
Hi @pszemraj, yes. We are planning to release the full dataset as soon as we can. It will be available on HuggingFace Hub. I'll keep this issue open and let you know when it's done. Thank you for your patience in the meantime!

**Comment by pszemraj** [comment]
No worries, understand that these things take time. Thank you!

**Comment by vipulraheja** [comment]
Hi @pszemraj, the dataset is now available on [Hugging Face](https://huggingface.co/datasets/grammarly/coedit).

**Comment by pszemraj** [comment]
thank you!

**Comment by leekum2018** [comment]
> Hi @pszemraj, the dataset is now available on [Hugging Face](https://huggingface.co/datasets/grammarly/coedit).

@vipulraheja Hello, the link is unavailable.  Is there any other way to  access the data?

**Comment by vipulraheja** [comment]
@leekum2018 it should be available now.

**Comment by vipulraheja** [comment]
@leekum2018 it should be available now.
